name: coffeshop
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.0
  clickable_widget: ^0.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  google_fonts: ^6.0.0
  iconify_flutter: ^0.0.5
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
  - family : fontisto
  assets:
    - assets/images/hal1.jpg
    - assets/images/loginpage.jpg
    - assets/images/logo_google.jpg
    - assets/images/orang.png
    - assets/images/kopi.jpg
    - assets/images/kopi2.jpg
    - assets/images/api.png
    - assets/images/offer.jpg
    - assets/images/me.JPG
    - assets/images/me.png
    - assets/images/aero.jpg
    - assets/images/coldbrew.jpg
    - assets/images/french.jpg
    - assets/images/v60.jpg
    - assets/images/vdrip.jpeg
    - assets/images/kopiaren.jpg
    - assets/images/smachi.jpg
    - assets/images/lmachi.jpg
    - assets/images/lungo.jpg
    - assets/images/amerikano.jpg

